language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
before_script:
  - nvm install 6
  - nvm use 6
  - npm i -g npm@4
  - npm i -g @angular/cli
  - npm i
  - touch tests.db
  - chmod a+w tests.db
after_success:
  - echo -e "<?php\n  print phpversion();" > version.php
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  - ./dropbox_uploader.sh -f /dev/null upload coverage/api coverage-$(php version.php)/
  - ./dropbox_uploader.sh -f /dev/null upload coverage/app coverage-$(php version.php)/

